config/routes.rb
Rails.application.routes.draw do
  get 'relacions/create'

  resources :articulos, :only => [:new, :show, :create, :index]
  
  resources :comentarios, :only => [:create]
  
  resources :usuarios, :only => [:new, :create]

  resources :categorias, :only => [:new, :show]
  
  resources :relacions, :only => [:create]
  
  post 'aagrega_categoria' => "categorias#create", :as => 'categoria_index'

  get 'acceder' => "sessions#new", :as => 'login'

  post 'acceso' => "sessions#create", :as => 'acceso'

  post 'cerrar' => 'sessions#destroy', :as => 'log_out'

  get 'cerrar' => 'sessions#destroy'

  root "paginas#bienvenido"

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base

	has_many :comentarios

	has_many :relacions

	has_many :categorias, through: :relacions
	
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

has_many :relacions

has_many :articulos, through: :relacions 
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base

	belongs_to :articulo
	belongs_to :usuario

end

app/models/relacion.rb
class Relacion < ActiveRecord::Base


 belongs_to :articulo

 belongs_to :categoria
 
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

	has_secure_password

	validates :nombre_usuario, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :usuario_autenticado, :autenticado?

  def usuario_autenticado
  	@current_user ||= Usuario.find(session[:user]) if session[:user]
  end

  def autenticado?

  	!!usuario_autenticado #true

  end

  def required_user

  	if !autenticado? 
  		redirect_to login_path
  	end	
  end

end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  
  before_action :set_articulo, :only => [:show]

  before_filter :required_user, :only => [:new, :create]
  
  def index
  	@articulos = Articulo.all
  end

  def new
  	@articulo = Articulo.new
  end

  def create
  	@articulo = Articulo.new(articulo_params)

  	if @articulo.save

  		redirect_to @articulo

  	else

  		render 'new'

  	end

  end

  def show
  	@comentarios = Comentario.all
  	@comentario = Comentario.new
    @relacion = Relacion.new
    @categorias = @articulo.categorias
  end

  private

  def articulo_params
  	params.require(:articulo).permit(:titulo, :descripcion)
  end

  def set_articulo
  	@articulo = Articulo.find(params[:id])
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  
  def new
    @categoria = Categoria.new
  end

  def create

  	@categoria = Categoria.new(categoria_params)

   if @categoria.save

   	redirect_to new_categoria_path

   else

   	render 'new'

   end

  end

  def show

    @categoria = Categoria.find(params[:id])
    @articulos = @categoria.articulos

  end

  private

  def categoria_params

  	params.require(:categoria).permit(:nombre)

  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  
  before_filter :authenticate_usuario!, :except => [:list, :show] 

  def create

   @comentario = Comentario.new(comentario_params)

   if @comentario.save

   	@articulo = @comentario.articulo 
   	redirect_to @articulo

   else

   	render 'new'

   end

  end

  private

  def comentario_params

  	params.require(:comentario).permit(:contenido, :articulo_id)

  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController

  #before_filter :authenticate_usuario!

  def bienvenido
  end
end

app/controllers/relacions_controller.rb
class RelacionsController < ApplicationController
  def create
    @relacion = Relacion.new(relacion_params)

   if @relacion.save

   	@articulo = Articulo.find(@relacion.articulo_id)
   	#@articulo = @relacion.articulo_id
   	redirect_to @articulo
   else

   	render 'new'

   end

  end

  private

  def relacion_params

  	params.require(:relacion).permit(:categoria_id, :articulo_id)

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create

    usuario = Usuario.find_by_nombre_usuario(params[:nombre_usuario])

    if usuario && usuario.authenticate(params[:password])

      session[:user] = usuario.id
      redirect_to root_path

    else

    render 'new'

    end

  end

  def destroy
    session[:user] = nil
    redirect_to root_path
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
  	@usuario = Usuario.new
  end

  def create
	@usuario = Usuario.new(usuario_params)

  	if @usuario.save

  		redirect_to root_path

  	else

  		render 'new'

  	end

  end

  private

  def usuario_params
  	params.require(:usuario).permit(:nombre_usuario, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/relacions_helper.rb
module RelacionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/articulos/create.html.erb
<h1>Articulos#create</h1>
<p>Find me in app/views/articulos/create.html.erb</p>

app/views/articulos/index.html.erb
<h2> TODO LOS ARTICULOS </h2>

<% @articulos.each do |a| %>

	<%= link_to a.titulo,  articulo_path(a) %> <br />

<% end %>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

<%= form_for (@articulo) do |a| %>

<%= a.label :titulo %> <br />
<%= a.text_field :titulo %> <br />
<%= a.label :descripcion %> <br />
<%= a.text_area :descripcion, :size => "22x8" %>
<br />
<br />
<%= a.submit 'Çrea Articulo' %>

<% end %>

app/views/articulos/show.html.erb
<h1>Articulos#show</h1>
<p>Find me in app/views/articulos/show.html.erb</p>

<h2><%= @articulo.titulo %></h2> <br />

<%= @articulo.descripcion %>

<p>
	Categorias de este articulo:

	<% @categorias.each do |c| %>

	<%= link_to c.nombre, categoria_path(c) %>

	<% end %>
<p>

Agrega Categoria
</p>

<%= form_for (@relacion) do |a| %>

<%= a.collection_select(:categoria_id, Categoria.all, :id, :nombre) %>
<%= a.hidden_field :articulo_id, :value => params[:id] %>

<%= a.submit 'Asigna Categoria >>'%>
<% end %>

<hr>
<ul>
<% @comentarios.each do |c| %>

<li><%= c.contenido %> </li>

<% end %>
</ul>
<h4> Escriber un comentario </h4>
<%= form_for (@comentario) do |c| %>

<%= c.text_field :contenido, :placeholder => "Inserta un comentario" %>
<%= c.hidden_field :articulo_id, :value => params[:id] %>
<%= c.submit 'Enviar' %>

<% end %>

app/views/categorias/new.html.erb
<h1>Categorias#new</h1>
<p>Find me in app/views/categorias/new.html.erb</p>

<%= form_for (@categoria) do |a| %>

<%= a.label :nombre %> <br />
<%= a.text_field :nombre %> <br />
<br />
<br />
<%= a.submit 'Categoria' %>

<% end %>

app/views/categorias/show.html.erb
<h1>Categorias#new</h1>
<p>Find me in app/views/categorias/new.html.erb</p>

<p> 

	Estas en la Categoria <%= @categoria.nombre %>

</p>

<P> Los articulos de esta cataegoria son </p>

<ul>
	<% @articulos.each do |a| %>

	<li><%= link_to a.titulo, articulo_path(a)  %></li>

	<% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Toggle navigation
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blog Colegio', root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if autenticado? %>
        <li class="active"><%= link_to 'Agrega Categoria', new_categoria_path %></li> 
        <li><%= link_to 'Crea Articulo', new_articulo_path %></li>
        <li><%= link_to 'Todos los Articulos', articulos_path %></li>
        <% else %>

        <li><%= link_to 'Acceder', login_path %> </li>

		<li><%= link_to 'Registrarse', new_usuario_path %> </li>
      	<% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      	<% if autenticado? %>
        <li><%= link_to 'Cerrar Sesion', log_out_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>









</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/paginas/bienvenido.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
<h1>HOLA BIENVENIDO!</h1>
		</div>
		<div class="col-md-6">
			<%= link_to 'Crea Articulo', new_articulo_path %> 

<%= link_to 'Todos los Articulos', articulos_path %> 
		</div>
	</div>
</div>

app/views/relacions/create.html.erb
<h1>Relacions#create</h1>
<p>Find me in app/views/relacions/create.html.erb</p>

app/views/usuarios/create.html.erb
<h1>Usuarios#create</h1>
<p>Find me in app/views/usuarios/create.html.erb</p>

app/views/usuarios/new.html.erb
<h1>Usuarios#new</h1>
<p>Find me in app/views/usuarios/new.html.erb</p>

<%= form_for (@usuario) do |u| %>
<% if @usuario.errors.any? %>

<%= @usuario.errors.full_messages.join("<br />").html_safe %> <br />

<% end %>

<%= u.label :nombre_usuario %> <br />
<%= u.text_field :nombre_usuario %> <br />

<%= u.label :password %> <br />
<%= u.password_field :password %> <br /><br />

<%= u.label :password_confirmation %> <br />
<%= u.password_field :password_confirmation %> <br /><br />

<%= u.submit 'Crear Usuario' %>

<% end %>